name: build-test
on:
  pull_request:
  push:
    branches:
      - gnome-42-2204-sdk
      - gnome-46-2404-sdk

jobs:
  snap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1
      id: snapcraft
    - uses: actions/upload-artifact@v2
      with:
        name: 'snap'
        path: ${{ steps.snapcraft.outputs.snap}}
